### ISSUE TITLE
Invalid default config

### ISSUE THREAD

**Issue by nlehuby** [ad-freiburg/pfaedle#1]
When trying the example in the `README`, there is an error while parsing the default config:
```
pfaedle -D -x freiburg-regbez-latest.osm .
[2019-02-11 07:25:05.053] ERROR: Could not parse MOT configurations, reason was:
~/pfaedle/pfaedle.cfg:8, at pos 25: Expected <valid regular expression>, found <regex error: '\[': regex_error>
```

**Comment by patrickbr** [comment]
Which compiler are you using? <regex> is incomplete in gcc versions earlier than 4.9, see for example [this thread](https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions).

**Comment by nlehuby** [comment]
I use
* gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
* clang version 5.0.0 (tags/RELEASE_500/final)

**Comment by nlehuby** [comment]
can't compile with gcc 4.9.4
```shell
In file included from ~/build/nlehuby/pfaedle/src/pfaedle/config/ConfigReader.cpp:10:
In file included from ~/build/nlehuby/pfaedle/src/pfaedle/Def.h:8:
~/build/nlehuby/pfaedle/src/util/geo/Geo.h:745:27: error: no member
      named 'runtime_error' in namespace 'std'
    if (b > e) throw std::runtime_error("Could not parse WKT");
                     ~~~~~^
~/build/nlehuby/pfaedle/src/util/geo/Geo.h:747:35: error: no member
      named 'runtime_error' in namespace 'std'
    if (xy.size() < 2) throw std::runtime_error("Could not parse WKT");
                             ~~~~~^
~/build/nlehuby/pfaedle/src/util/geo/Geo.h:752:14: error: no member
      named 'runtime_error' in namespace 'std'
  throw std::runtime_error("Could not parse WKT");
        ~~~~~^
~/build/nlehuby/pfaedle/src/util/geo/Geo.h:763:27: error: no member
      named 'runtime_error' in namespace 'std'
    if (b > e) throw std::runtime_error("Could not parse WKT");
                     ~~~~~^
~/build/nlehuby/pfaedle/src/util/geo/Geo.h:767:37: error: no member
      named 'runtime_error' in namespace 'std'
      if (xy.size() < 2) throw std::runtime_error("Could not parse WKT");
                               ~~~~~^
~/build/nlehuby/pfaedle/src/util/geo/Geo.h:774:14: error: no member
      named 'runtime_error' in namespace 'std'
  throw std::runtime_error("Could not parse WKT");
        ~~~~~^
6 errors generated.
make[2]: *** [src/pfaedle/CMakeFiles/pfaedle_dep.dir/config/ConfigReader.cpp.o] Error 1
make[1]: *** [src/pfaedle/CMakeFiles/pfaedle_dep.dir/all] Error 2
make: *** [all] Error 2
The command "sudo make install" failed and exited with 2 during .
```

**Comment by patrickbr** [comment]
Sorry, there was missing include. Can you try the latest commit?

**Comment by nlehuby** [comment]
it works, thanks :+1:
